In [1]:
#calling the necessary libraries

import pandas as pd
import requests
from bs4 import BeautifulSoup

# Now we will get the url of the site and will store all the pages of the site in a variable

In [2]:
url = 'https://www.imdb.com/list/ls068082370/'
all=[]
while(url != None):
    all.append(url)
    page=requests.get(url)
    soup = BeautifulSoup(page.text,'html.parser')
    next=soup.find_all(class_="flat-button lister-page-next next-page")
    if (len(next)==0):
        url= None
    else:
        next="https://www.imdb.com" + next[0].get('href')
        url=next
all

['https://www.imdb.com/list/ls068082370/',
 'https://www.imdb.com/list/ls068082370/?page=2',
 'https://www.imdb.com/list/ls068082370/?page=3']

# We will now start working with the contents of the pages now

In [3]:
#while storing the information of directors we found that the directors and stars are stored together.
#Thus we have created a function, that will store the names of the directors and stars separately.


def d_a(d):
    d=d.replace('\n',"")
    d=d.replace('|',"")
    d=d.split('Stars:')
    d[0]=d[0].replace("Directors:","")
    d[0]=d[0].replace("Director:","")
    for i in range(10):
        d[0]=d[0].replace("  "," ")
    director=d[0][1:]
    stars=d[1]
    stars=stars.replace(":","")
    
    return director,stars

In [4]:
#The same problem has been found while working with the gross and votes.
#Similarly, we have created this function to separate the gross and the votes value

def v_g(v):
    vg_list=[]
    for i in v:
        vg_list.append(i.text)
    if(len(v)==2):
        votes=vg_list[0]
        gross=vg_list[1]
    else:
        votes=vg_list[0]
        gross=None
    
    return votes,gross

# Now that we have done separating with the different contents of the movies. We will pass all those informations in a final array.

In [5]:
final = []
for i in all:
    page=requests.get(i)
    soup = BeautifulSoup(page.text,'html.parser')
    for j in soup.find_all(class_='lister-item-content'):
        ids =int(j.find('span',{"class":'lister-item-index unbold text-primary'}).text[:-1])
        movie=j.find('a').text
        year=j.find('span',{'class':'lister-item-year text-muted unbold'}).text[1:5]
        genre=j.find('span',{'class':'genre'}).text[1:]
        time = j.find('span',{'class':'runtime'}).text
        imdb=j.find('span',{'class':'ipl-rating-star__rating'}).text
        rating=j.find('span',{'class':'ipl-rating-star__rating'}).text
        summary=j.find_all('p')[1].text[5:]
        director,stars=d_a(j.find_all('p',{'class':'text-muted text-small'})[1].text)
        votes,gross=v_g(j.find_all('span',{'name':'nv'}))
        Add=[ids,movie,year,genre,time,imdb,rating,summary,director,stars,votes,gross]
        final.append(Add)

# Now that we have stored all the required informations in separate columns. We will name our columns accordingly.

In [6]:
column=['ID','Movie name','Released Year','Genre','Time Length of the movie','IMDB','Ratings','Movie Summary','Directors','Stars','Votes','Gross']

# We will then convert the thing into a dataframe.

In [7]:
data=pd.DataFrame(final,columns=column)

# This is how our dataframe looks like.

In [8]:
data

,ID,Movie name,Released Year,Genre,Time Length of the movie,IMDB,Ratings,Movie Summary,Directors,Stars,Votes,Gross
0,1,The Shawshank Redemption,1994,Drama,142 min,9.3,9.3,Two imprisoned men bond over a number of years...,Frank Darabont,"Tim Robbins, Morgan Freeman, Bob Gunton, Willi...","2,124,085",$28.34M
1,2,The Godfather,1972,"Crime, Drama",175 min,9.2,9.2,The aging patriarch of an organized crime dyna...,Francis Ford Coppola,"Marlon Brando, Al Pacino, James Caan, Diane Ke...","1,458,401",$134.97M
2,3,The Dark Knight,2008,"Action, Crime, Drama",152 min,9,9,When the menace known as The Joker emerges fro...,Christopher Nolan,"Christian Bale, Heath Ledger, Aaron Eckhart, M...","2,089,192",$534.86M
3,4,The Godfather: Part II,1974,"Crime, Drama",202 min,9,9,The early life and career of Vito Corleone in ...,Francis Ford Coppola,"Al Pacino, Robert De Niro, Robert Duvall, Dian...","1,014,324",$57.30M
4,5,Pulp Fiction,1994,"Crime, Drama",154 min,8.9,8.9,"The lives of two mob hitmen, a boxer, a gangst...",Quentin Tarantino,"John Travolta, Uma Thurman, Samuel L. Jackson,...","1,663,903",$107.93M
5,6,Schindler's List,1993,"Biography, Drama, History",195 min,8.9,8.9,"In German-occupied Poland during World War II,...",Steven Spielberg,"Liam Neeson, Ralph Fiennes, Ben Kingsley, Caro...","1,102,206",$96.90M
6,7,The Lord of the Rings: The Return of the King,2003,"Adventure, Drama, Fantasy",201 min,8.9,8.9,Gandalf and Aragorn lead the World of Men agai...,Peter Jackson,"Elijah Wood, Viggo Mortensen, Ian McKellen, Or...","1,511,292",$377.85M
7,8,12 Angry Men,1957,Drama,96 min,8.9,8.9,A jury holdout attempts to prevent a miscarria...,Sidney Lumet,"Henry Fonda, Lee J. Cobb, Martin Balsam, John ...","604,939",$4.36M
8,9,"Il buono, il brutto, il cattivo",1966,Western,161 min,8.8,8.8,A bounty hunting scam joins two men in an unea...,Sergio Leone,"Clint Eastwood, Eli Wallach, Lee Van Cleef, Al...","630,943",$6.10M
9,10,Forrest Gump,1994,"Drama, Romance",142 min,8.8,8.8,"The presidencies of Kennedy and Johnson, the e...",Robert Zemeckis,"Tom Hanks, Robin Wright, Gary Sinise, Sally Field","1,633,407",$330.25M
10,11,Inception,2010,"Action, Adventure, Sci-Fi",148 min,8.8,8.8,A thief who steals corporate secrets through t...,Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen...","1,862,343",$292.58M
11,12,The Lord of the Rings: The Fellowship of the Ring,2001,"Adventure, Drama, Fantasy",178 min,8.8,8.8,A meek Hobbit from the Shire and eight compani...,Peter Jackson,"Elijah Wood, Ian McKellen, Orlando Bloom, Sean...","1,526,848",$315.54M
12,13,Fight Club,1999,Drama,139 min,8.8,8.8,An insomniac office worker and a devil-may-car...,David Fincher,"Brad Pitt, Edward Norton, Meat Loaf, Zach Grenier","1,697,797",$37.03M
13,14,Dangal,2016,"Action, Biography, Drama",161 min,8.4,8.4,Former wrestler Mahavir Singh Phogat and his t...,Nitesh Tiwari,"Aamir Khan, Sakshi Tanwar, Fatima Sana Shaikh,...","127,047",$12.39M
14,15,Star Wars: Episode V - The Empire Strikes Back,1980,"Action, Adventure, Fantasy",124 min,8.7,8.7,After the Rebels are brutally overpowered by t...,Irvin Kershner,"Mark Hamill, Harrison Ford, Carrie Fisher, Bil...","1,063,663",$290.48M
15,16,Star Wars,1977,"Action, Adventure, Fantasy",121 min,8.6,8.6,Luke Skywalker joins forces with a Jedi Knight...,George Lucas,"Mark Hamill, Harrison Ford, Carrie Fisher, Ale...","1,132,675",$322.74M
16,17,The Matrix,1999,"Action, Sci-Fi",136 min,8.7,8.7,A computer hacker learns from mysterious rebel...,"Lana Wachowski, Lilly Wachowski","Keanu Reeves, Laurence Fishburne, Carrie-Anne ...","1,527,953",$171.48M
17,18,Goodfellas,1990,"Biography, Crime, Drama",146 min,8.7,8.7,The story of Henry Hill and his life in the mo...,Martin Scorsese,"Robert De Niro, Ray Liotta, Joe Pesci, Lorrain...","917,554",$46.84M
18,19,One Flew Over the Cuckoo's Nest,1975,Drama,133 min,8.7,8.7,A criminal pleads insanity after getting into ...,Milos Forman,"Jack Nicholson, Louise Fletcher, Will Sampson,...","840,761",$112.00M
19,20,Cidade de Deus,2002,"Crime, Drama",130 min,8.6,8.6,"In the slums of Rio, two kids' paths diverge a...","Fernando Meirelles, Kátia Lund","Alexandre Rodrigues, Leandro Firmino, Matheus ...","651,204",$7.56M
20,21,The Lord of the Rings: The Two Towers,2002,"Adventure, Drama, Fantasy",179 min,8.7,8.7,While Frodo and Sam edge closer to Mordor with...,Peter Jackson,"Elijah Wood, Ian McKellen, Viggo Mortensen, Or...","1,366,746",$342.55M
21,22,Shichinin no samurai,1954,"Adventure, Drama",207 min,8.6,8.6,A poor village under attack by bandits recruit...,Akira Kurosawa,"Toshirô Mifune, Takashi Shimura, Keiko Tsushim...","287,847",$0.27M
22,23,Interstellar,2014,"Adventure, Drama, Sci-Fi",169 min,8.6,8.6,A team of explorers travel through a wormhole ...,Christopher Nolan,"Matthew McConaughey, Anne Hathaway, Jessica Ch...","1,319,390",$188.02M
23,24,Kimi no na wa.,2016,"Animation, Drama, Fantasy",106 min,8.4,8.4,Two strangers find themselves linked in a biza...,Makoto Shinkai,"Ryûnosuke Kamiki, Mone Kamishiraishi, Ryô Nari...","140,206",$5.02M
24,25,The Silence of the Lambs,1991,"Crime, Drama, Thriller",118 min,8.6,8.6,A young F.B.I. cadet must receive the help of ...,Jonathan Demme,"Jodie Foster, Anthony Hopkins, Lawrence A. Bon...","1,149,572",$130.74M
25,26,Léon,1994,"Action, Crime, Drama",110 min,8.6,8.6,"Mathilda, a 12-year-old girl, is reluctantly t...",Luc Besson,"Jean Reno, Gary Oldman, Natalie Portman, Danny...","938,552",$19.50M
26,27,Se7en,1995,"Crime, Drama, Mystery",127 min,8.6,8.6,"Two detectives, a rookie and a veteran, hunt a...",David Fincher,"Morgan Freeman, Brad Pitt, Kevin Spacey, Andre...","1,304,478",$100.13M
27,28,Saving Private Ryan,1998,"Drama, War",169 min,8.6,8.6,"Following the Normandy Landings, a group of U....",Steven Spielberg,"Tom Hanks, Matt Damon, Tom Sizemore, Edward Burns","1,125,272",$216.54M
28,29,The Usual Suspects,1995,"Crime, Mystery, Thriller",106 min,8.5,8.5,A sole survivor tells of the twisty events lea...,Bryan Singer,"Kevin Spacey, Gabriel Byrne, Chazz Palminteri,...","916,755",$23.34M
29,30,Sen to Chihiro no kamikakushi,2001,"Animation, Adventure, Family",125 min,8.6,8.6,"During her family's move to the suburbs, a sul...","Hayao Miyazaki, Kirk Wise","Daveigh Chase, Suzanne Pleshette, Miyu Irino, ...","566,507",$10.06M
...,...,...,...,...,...,...,...,...,...,...,...,...
220,221,The Wizard of Oz,1939,"Adventure, Family, Fantasy",102 min,8,8,Dorothy Gale is swept away from a farm in Kans...,"Victor Fleming, George Cukor, Mervyn LeRoy, No...","Judy Garland, Frank Morgan, Ray Bolger, Bert Lahr","354,932",$2.08M
221,222,Rush,I) (,"Action, Biography, Drama",123 min,8.1,8.1,The merciless 1970s rivalry between Formula On...,Ron Howard,"Daniel Brühl, Chris Hemsworth, Olivia Wilde, A...","397,383",$26.95M
222,223,The Truman Show,1998,"Comedy, Drama, Sci-Fi",103 min,8.1,8.1,An insurance salesman discovers his whole life...,Peter Weir,"Jim Carrey, Ed Harris, Laura Linney, Noah Emme...","848,130",$125.62M
223,224,Platoon,1986,"Drama, War",120 min,8.1,8.1,A young soldier in Vietnam faces a moral crisi...,Oliver Stone,"Charlie Sheen, Tom Berenger, Willem Dafoe, Kei...","354,635",$138.53M
224,225,Million Dollar Baby,2004,"Drama, Sport",132 min,8.1,8.1,A determined woman works with a hardened boxin...,Clint Eastwood,"Hilary Swank, Clint Eastwood, Morgan Freeman, ...","591,119",$100.49M
225,226,The Bourne Ultimatum,2007,"Action, Mystery, Thriller",115 min,8,8,Jason Bourne dodges a ruthless C.I.A. official...,Paul Greengrass,"Matt Damon, Edgar Ramírez, Joan Allen, Julia S...","582,077",$227.47M
226,227,Stalker,1979,"Drama, Sci-Fi",162 min,8.2,8.2,A guide leads two men through an area known as...,Andrei Tarkovsky,"Alisa Freyndlikh, Aleksandr Kaydanovskiy, Anat...","99,736",$0.23M
227,228,Relatos salvajes,2014,"Comedy, Drama, Thriller",122 min,8.1,8.1,Six short stories that explore the extremities...,Damián Szifron,"Darío Grandinetti, María Marull, Mónica Villa,...","153,550",$3.11M
228,229,Hachi: A Dog's Tale,2009,"Drama, Family",93 min,8.1,8.1,A college professor bonds with an abandoned do...,Lasse Hallström,"Richard Gere, Joan Allen, Cary-Hiroyuki Tagawa...","226,362",None
229,230,How to Train Your Dragon,2010,"Animation, Action, Adventure",98 min,8.1,8.1,A hapless young Viking who aspires to hunt dra...,"Dean DeBlois, Chris Sanders","Jay Baruchel, Gerard Butler, Christopher Mintz...","617,581",$217.58M
230,231,Annie Hall,1977,"Comedy, Romance",93 min,8,8,Neurotic New York comedian Alvy Singer falls i...,Woody Allen,"Woody Allen, Diane Keaton, Tony Roberts, Carol...","238,002",$39.20M
231,232,Ben-Hur,1959,"Adventure, Drama, History",212 min,8.1,8.1,When a Jewish prince is betrayed and sent into...,William Wyler,"Charlton Heston, Jack Hawkins, Stephen Boyd, H...","203,310",$74.70M
232,233,Before Sunrise,1995,"Drama, Romance",101 min,8.1,8.1,A young man and woman meet on a train in Europ...,Richard Linklater,"Ethan Hawke, Julie Delpy, Andrea Eckert, Hanno...","241,246",$5.54M
233,234,Faa yeung nin wa,2000,"Drama, Romance",98 min,8.1,8.1,"Two neighbors, a woman and a man, form a stron...",Kar-Wai Wong,"Tony Chiu-Wai Leung, Maggie Cheung, Ping Lam S...","107,386",$2.73M
234,235,Hotel Rwanda,2004,"Biography, Drama, History",121 min,8.1,8.1,Paul Rusesabagina was a hotel manager who hous...,Terry George,"Don Cheadle, Sophie Okonedo, Joaquin Phoenix, ...","315,615",$23.53M
235,236,Butch Cassidy and the Sundance Kid,1969,"Biography, Crime, Drama",110 min,8,8,"Wyoming, early 1900s. Butch Cassidy and The Su...",George Roy Hill,"Paul Newman, Robert Redford, Katharine Ross, S...","189,013",$102.31M
236,237,Gandhi,1982,"Biography, Drama, History",191 min,8,8,Gandhi's character is fully explained as a man...,Richard Attenborough,"Ben Kingsley, John Gielgud, Rohini Hattangadi,...","208,812",$52.77M
237,238,Barry Lyndon,1975,"Adventure, Drama, History",185 min,8.1,8.1,An Irish rogue wins the heart of a rich widow ...,Stanley Kubrick,"Ryan O'Neal, Marisa Berenson, Patrick Magee, H...","134,066",None
238,239,Salinui chueok,2003,"Action, Crime, Drama",131 min,8.1,8.1,"In a small Korean province in 1986, three dete...",Joon-ho Bong,"Kang-ho Song, Sang-kyung Kim, Roe-ha Kim, Jae-...","103,344",$0.01M
239,240,Life of Brian,1979,Comedy,94 min,8.1,8.1,Born on the original Christmas in the stable n...,Terry Jones,"Graham Chapman, John Cleese, Michael Palin, Te...","338,052",$20.05M
240,241,Mou gaan dou,2002,"Crime, Drama, Mystery",101 min,8.1,8.1,A story between a mole in the police departmen...,"Andrew Lau Wai-Keung, Alan Mak","Andy Lau, Tony Chiu-Wai Leung, Anthony Chau-Sa...","111,489",$0.17M
241,242,La haine,1995,"Crime, Drama",98 min,8.1,8.1,24 hours in the lives of three young men in th...,Mathieu Kassovitz,"Vincent Cassel, Hubert Koundé, Saïd Taghmaoui,...","133,242",$0.31M
242,243,In the Name of the Father,1993,"Biography, Drama",133 min,8.1,8.1,A man's coerced confession to an IRA bombing h...,Jim Sheridan,"Daniel Day-Lewis, Pete Postlethwaite, Alison C...","142,931",$25.01M
243,244,Amores perros,2000,"Drama, Thriller",154 min,8.1,8.1,A horrific car accident connects three stories...,Alejandro G. Iñárritu,"Emilio Echevarría, Gael García Bernal, Goya To...","208,493",$5.38M
244,245,Network,1976,Drama,121 min,8.1,8.1,A television network cynically exploits a dera...,Sidney Lumet,"Faye Dunaway, William Holden, Peter Finch, Rob...","132,793",None
245,246,Kaze no tani no Naushika,1984,"Animation, Adventure, Fantasy",117 min,8.1,8.1,Warrior and pacifist Princess Nausicaä despera...,Hayao Miyazaki,"Sumi Shimamoto, Mahito Tsujimura, Hisako Kyôda...","129,778",$0.50M
246,247,The Maltese Falcon,1941,"Film-Noir, Mystery",100 min,8,8,A private detective takes on a case that invol...,John Huston,"Humphrey Bogart, Mary Astor, Gladys George, Pe...","141,566",$2.11M
247,248,Persona,1966,"Drama, Thriller",85 min,8.1,8.1,A nurse is put in charge of a mute actress and...,Ingmar Bergman,"Bibi Andersson, Liv Ullmann, Margaretha Krook,...","88,421",None
248,249,The Grapes of Wrath,1940,"Drama, History",129 min,8,8,A poor Midwest family is forced off their land...,John Ford,"Henry Fonda, Jane Darwell, John Carradine, Cha...","81,640",$0.06M
249,250,Jaws,1975,"Adventure, Drama, Thriller",124 min,8,8,When a killer shark unleashes chaos on a beach...,Steven Spielberg,"Roy Scheider, Robert Shaw, Richard Dreyfuss, L...","515,780",$260.00M

# Our dataframe is ready with 250 rows and 12 columns.

# The rows contains different movie names whereas the column contains the different movie details.

In [9]:
data.shape

(250, 12)